from cs1graphics import *
c=Canvas(400,500,"cyan","Three shapes)")
mySquare = Square(50,Point(100,50))
c.add(mySquare)
mySquare.setFillColor("black")
myCircle = Circle(100,Point(200,250))
c.add(myCircle)
myCircle.setFillColor("red")
myCircle.setBorderColor("red")
myRectangle = Rectangle(70,90,Point(300,400))
myRectangle.setFillColor("orange")
c.add(myRectangle)
myRectangle.setBorderColor("white")
myRectangle.setBorderWidth(20)
myShape = Polygon(Point(200,100),Point(30,40),Point(60,100))
c.add(myShape)
myShape.setFillColor("purple")
myShape.setDepth(100)
